In [1]:
# Numpy的核心内容之一时N维数组对象——ndarray。一个ndarray对象通常是一个统统的多维同类数据容器，
# 即，它包含的每一个元素均为相同类型。ndarray对象有dtype属性和shape属性分别用来描述数组的数据
# 类型和数组每一维度上元素的数量（数组形状）。
# import numpy as np 是约定俗称的numpy导入方式；
import numpy as np

In [4]:
# 生成ndarray数组的方式比较多，方便不同的使用需求
# 使用最简单的np.array()函数生成，array函数接收任意的序列型对象（比如列表、集合、元组以及数组等），以列表为例：
list1 = [1, 2, 3, 4, 5, 6]
arr1 = np.array(list1)
print(type(arr1), arr1)

<class 'numpy.ndarray'> [1 2 3 4 5 6]


In [6]:
# 如果是嵌套序列且等长度，则会转换成多维数组：
list2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(list2)
print(type(arr2), arr2)

<class 'numpy.ndarray'> [[1 2 3 4]
 [5 6 7 8]]


In [7]:
# 上面生成的多维数组可以使用属性ndim或shape来检验它的维数和每一维度上的元素数量
print(arr2.ndim)  # 输出2
print(arr2.shape)  # 输出(2, 4)

2
(2, 4)


In [8]:
# 当然，np.array函数生成数组的方法比较简单， 但是前提是需要一个序列型对象进行转换
# 而像常用的类似单位矩阵的数组使用np.array方法比较麻烦，那么np.eys()正好就解决了这个问题
# np.eye()和 np.identity()用来生成给定维度的方阵
arr3 = np.eye(3)  # 生成一个3*3的单位矩阵
print(arr3, arr3.shape)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)


In [10]:
# 类似地， np.ones()和np.zeros()生成给定shape属性的全为1或全为0的数组
arr4 = np.ones((2, 3))
arr5 = np.zeros((3, 3))
print(arr4, arr4.shape)
print(arr5, arr5.shape)

[[1. 1. 1.]
 [1. 1. 1.]] (2, 3)
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] (3, 3)


In [11]:
# 如果需要生成一个随机数组成的指定shape的数组，则使用np.random.random()
# 函数，传入shape参数即可
arr6 = np.random.random((2, 3))
print(arr6, arr6.shape)

[[0.40318059 0.68030606 0.08274558]
 [0.24822664 0.5582888  0.79787825]] (2, 3)


In [12]:
# 和Python内建函数range一样， 有时候用于迭代，numpy中对应存在np.arange()函数
# 用于生成指定范围的一维数组
arr7 = np.arange(1, 7)  # (1, 7)相当于一个左闭右开的区间，即不包含末尾的数字
print(arr7)

[1 2 3 4 5 6]


In [14]:
# 对于ones, zeros, 衍生出ones_like()和zeros_like()函数，
# 传入已有的数组， 然后生成和该数组shape一样的全为1或全为0的数组
arr8 = np.ones_like(arr3)
print(arr8, arr8.shape==arr3.shape)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] True


In [17]:
# 如果想要生成特定shape的数组且指定一个填入的数值， 则使用np.full()函数
arr9 = np.full(shape=(3, 2), fill_value=4, dtype=float)  # dtype用于指定数据类型
print(arr9)

[[4. 4.]
 [4. 4.]
 [4. 4.]]


In [18]:
# 类似地， full函数也衍生了full_like()函数
arr10 = np.full_like(arr9, fill_value=5, dtype=int)
print(arr10)

[[5 5]
 [5 5]
 [5 5]]


In [22]:
# empty函数和empty_like函数生成给定形状但没有初始化数值的空数组
arr11 = np.empty(shape=(2, 3), dtype=int)
arr11

array([[         0, 1072693248,          0],
       [1072693248,          0, 1072693248]])

In [23]:
# 上面的例子中也提到了dtype这个参数， 和shape参数一样， dtype也是ndarray
# 数组的属性，用来描述数组中元素的数据类型（因为数组中每一个元素的数据类型是一样的）
print(arr11.dtype)

int32


* ndarray的数据类型有
|类型|类型代码|描述|
|---:|---:|---:|
int8, uint8|i1,u1|有符号和无符号的8数位整数
int16,uimt16|i2,u2|有符号和无符号的16数位整数
int32,uint32|i4,u4|有符号和无符号的32数位整数
int64,uint64|i8,u8|有符号和无符号的64数位整数
float16|f2|半精度浮点数
float32|f4或f|标准单精度浮点数
float64|f8或d|标准双精度浮点数
float128|f16或g|拓展精度浮点数
complex64|c8,c16,c32|分别基于32位，64位，128位浮点数的复数
bool|?|布尔值， False或True
object|O|Python对象类型

In [32]:
# astype方法显示的转换数组的数据类型, 但不会改变对象的dtype属性，会生成一个新的对象
# 有些元素无法转换成另一类型时， 会抛出ValueError
arr12 = np.full_like(arr11, fill_value=2,dtype='float64')
print(arr12.dtype)

float64


In [34]:
arr12_1 = arr12.astype('int32')
print(arr12_1.dtype)

int32


In [35]:
# Numpy 数组运算
# 数组进行批量操作（对每一个元素进行同种操作）时不需要使用for循环
# 这种特性俗称向量化，任何两个等尺寸数组之间的算数操作都应用了主元素操作的方法
arr13 = np.array([[1,2,3,4],[4,5,6,7]])
arr14 = np.array([[11, 12, 13, 14], [15, 16, 17, 18]])
print(arr13 *arr13)  # 对arr13中的元素求平方操作

array([[ 1,  4,  9, 16],
       [16, 25, 36, 49]])

In [36]:
# 带有标量计算的算数操作，会把计算参数传递给数组的每一个元素
print(1/arr13)
print(arr13 * 2)
print(arr13 ** 2)
# 同尺寸数组之间的比较， 会产生一个布尔值数值
print(arr13 > arr14)

[[1.         0.5        0.33333333 0.25      ]
 [0.25       0.2        0.16666667 0.14285714]]
[[ 2  4  6  8]
 [ 8 10 12 14]]
[[ 1  4  9 16]
 [16 25 36 49]]
[[False False False False]
 [False False False False]]


In [38]:
# 基础索引与切片
# Numpy数组有很多种方式可以选中数据的子集或某个单个元素， 一维数组比较简单，看起来和Python的列表类似
print(arr1[1], arr1[:3])

2 [1 2 3]


In [41]:
# 不写切片数值[:]将会引用数组的所有值：
print(arr13[:])
# 如果想要一份数组切片的拷贝而不是视图的话的话，则必须显示的复制数组， 例如arr13[:].copy()
# 对于多维数组， 例如二维数组， 每一个索引值对应的元素不再是一个值， 而是一个一维数组
print(arr13[1])
# 如果要索引一个元素则在索引出来的一维数组的基础上按照一维数组的索引方法就可以完成索引
print(arr13[1][2])

[[1 2 3 4]
 [4 5 6 7]]
[4 5 6 7]
6


In [42]:
# 对于上面的例子，也可以把二维数组的行看作0轴， 列看作1轴
# 然后就可以使用逗号将行列索引分开,上面的例子可以写作：
print(arr13[1,2])
# 索引数据集
print(arr13[:2, 1:])

6
[[2 3 4]
 [5 6 7]]


In [44]:
# 布尔索引
# 在索引数组时可以传入布尔型数组，布尔索引数组长度必须和数组轴索引长度一致
bool_arr = np.arange(5) > 3
arr15 = np.random.randn(5, 4)
arr15[bool_arr, 1]

array([0.7895895])

In [47]:
bool_arr1 = np.arange(5) > 1
arr15[bool_arr1]

array([[ 0.04589525,  1.6603937 ,  0.61484664,  1.17613019],
       [-1.13439428,  0.24312946, -1.03262549,  0.56701778],
       [-0.75969684,  0.7895895 , -1.79792498, -0.47457082]])

In [50]:
# 如果要选择bool_arr中大于3或小于2的行， 则需要对布尔数组进行逻辑运算
bool_arr2 = (np.arange(5) > 3) | (np.arange(5) < 2)  # and的符号是&（python的and和or符号并不管用）
arr15[bool_arr2]

array([[-1.26031643,  1.05252461, -1.46200705, -1.0799147 ],
       [-0.52942307, -0.4520703 , -1.43713627, -0.06849401],
       [-0.75969684,  0.7895895 , -1.79792498, -0.47457082]])

In [51]:
# 也可以使用布尔索引对数组中符合某一条件的元素进行索引
# 将原数组转换成布尔数组就可以了
arr13[arr13 > 4]

array([5, 6, 7])

In [53]:
# 神奇索引
# 前面索引的多为数组行的顺序是按照原数组的顺序排列的
# 如果想要重新排列数组某个轴的顺序，可以使用神奇索引
arr16 = np.random.randn(5,4)
# 索引arr16数组中的第1，3，5行并且顺序是3， 1， 5
# 如果使用负的索引，将从尾部进行索引
arr16[[2, 0, 4]]

array([[ 1.09008397, -0.82377221,  0.55722343, -0.57005443],
       [ 0.93418829, -0.15033217,  0.66272027,  0.75219089],
       [ 0.42237579, -0.98225365, -0.6093055 ,  0.67896919]])

In [54]:
arr16[[-3, -2, -4]]

array([[ 1.09008397, -0.82377221,  0.55722343, -0.57005443],
       [ 0.06205233, -0.45251597,  0.28630007,  0.41260338],
       [-0.10573708,  0.95928264,  0.18703765,  0.19377178]])

In [56]:
# 同时， 神奇索引还可以配合切片索引使用
arr16[:, [0, 3, 1]]

array([[ 0.93418829,  0.75219089, -0.15033217],
       [-0.10573708,  0.19377178,  0.95928264],
       [ 1.09008397, -0.57005443, -0.82377221],
       [ 0.06205233,  0.41260338, -0.45251597],
       [ 0.42237579,  0.67896919, -0.98225365]])

In [58]:
# 数组的转置和换轴
# 在代数中， 矩阵的转置是非常常用的
# 在numpy中， 转置可以返回底层数据的视图而不需要复制任何内容， 数组拥有transpose方法和特殊的T属性
arr16_t = arr16.transpose()
print(arr16.shape, arr16_t.shape)

(5, 4) (4, 5)


In [61]:
print(arr16.T == arr16_t)

[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


In [62]:
# 上面是对于普通的二维数组的转置， 比较普遍
# 而对于高纬度的数组， tanspose方法可以接受包含轴编号的元组， 用于置换轴
arr3d = np.arange(27).reshape((3, 3, 3))
arr3d_t = arr3d.transpose((1, 0, 2))  # 是原先的第一个轴变成第一个轴， 第二个轴变成第一个轴
print(arr3d, arr3d_t)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]] [[[ 0  1  2]
  [ 9 10 11]
  [18 19 20]]

 [[ 3  4  5]
  [12 13 14]
  [21 22 23]]

 [[ 6  7  8]
  [15 16 17]
  [24 25 26]]]


In [64]:
# ndarray还有一个swapaxes方法， 该方法接受一对轴编号作为参数， 并对周进行调整用于重组数据
# 上面的示例用swapaxes表示为
arr3d.swapaxes(1, 0)
# swapaxes返回的是数组的视图，没有对数组数据进行复制

array([[[ 0,  1,  2],
        [ 9, 10, 11],
        [18, 19, 20]],

       [[ 3,  4,  5],
        [12, 13, 14],
        [21, 22, 23]],

       [[ 6,  7,  8],
        [15, 16, 17],
        [24, 25, 26]]])